### ISSUE TITLE
Fix npm link scripts between weaver-components and tamu-library-components

### ISSUE THREAD

**Issue by wwelling** [TAMULib/tamu-library-components#329]
Development requires the ability to use changes from weaver components without publishing a version to npm.

This was done as follows.

```
weaver-components/npm run build
weaver-components/npm run link

tamu-library-components/npm run link
tamu-library-components/npm run start
```

**Comment by kaladay** [comment]
Cannot reproduce.

**Comment by kaladay** [comment]
Was able to reproduce after a fresh npm install of node_modules.

In weaver-components:
```
npm install
npm run build
npm run link
```

In tamu-library-components:
```
npm install
npm run link
npm run build
```

Then error happens on `npm run build` in tamu-library-components.
