### ISSUE TITLE
Mobile Mega menu not expanding

### ISSUE THREAD

**Issue by mumptastic** [TAMULib/tamu-library-components#334]
iPhone users are not able to expand sub links in the the mega menu using Safari.

How to replicate the issue:
1.  Open Safari for iPhone
2. Visit https:/library.tamu.edu
3. Click on the 'hamburger' menu, the menu should open without any issues.
4. Click on any of the yellow navigation items. The `+` will rotate to an `x` but will not show sub links.

This needs to be verified on an actual device, or on the xcode emulator, if it can be reproduced in that environment.

It should be verified on all mobile platforms.

This needs to be confirmed as working on 1x

**Comment by kaladay** [comment]
I stumbled on this one in Chrome under Linux.

I think it could be related to the versions of the libraries used.

This does mean that this is not as isolated as initially thought.
