### ISSUE TITLE
TL components should implement `suppressTopNavList` in 1x

### ISSUE THREAD

**Issue by jeremythuff** [TAMULib/tamu-library-components#394]
This feature has been implemented in 2x here:

https://github.com/TAMULib/tamu-library-components/blob/master/projects/tl-elements/src/lib/tl-header/tl-header.component.ts#L51

It needs to be ported into the 1x branch

**Comment by kaladay** [comment]
I can reproduce this as working on sprint23 base branch by appending something like ` suppress-top-nav="libraries, information for"` to the `<tl-header>` element.
