### ISSUE TITLE
(EPIC) AXE dev-tools flagging weaver components as a serious ADA issue

### ISSUE THREAD

**Issue by artjynx** [TAMULib/tamu-library-components#422]
I am doing a random check for accessibility on the website using Axe dev tools chrome extension. It's flagging the weaver components as a serious issue..... see screenshot or just run the axe dev tool extension

<img width="2050" alt="image" src="https://user-images.githubusercontent.com/4729076/177812662-ced1cfcb-b2c0-4eff-bd3b-e6329dadf632.png">

**Comment by jcreel** [comment]
Decomposed into #423 #424 #425

**Comment by jcreel** [comment]
For this epic, the deliverables need to be pre-approved by Punit Gaddam, our Senior Accessibility Policy Analyst.  (Talk to Tina)
