### ISSUE TITLE
Fix tl-nav after hoisting wvr-nav-li-component out of ul.

### ISSUE THREAD

**Issue by kaladay** [TAMULib/tamu-library-components#432]
This is a sub-issue of the Epic:

- https://github.com/TAMULib/tamu-library-components/issues/422

This is a follow up to:
- https://github.com/TAMULib/weaver-components/issues/490

The tl-components now require changes that may require further changes to weaver-components to properly get this working.

![Screenshot_2022-09-06_10-54-30](https://user-images.githubusercontent.com/35114839/188681067-d67510e3-4600-4039-be02-a97e93f150e6.png)

**Comment by jcreel** [comment]
This is fixed by not hoisting and instead using aria roles.
